#!/usr/bin/env sh

ENV=${1:-gradle}

function prop {
    grep "${1}" ../${ENV}.properties|cut -d'=' -f2
}

PROJ_VERSION=$(prop 'lProjectVersion')

./gradlew clean
./gradlew bootJar
mkdir -p build/dependency && (cd build/dependency; jar -xf ../libs/*.jar)
docker build -t lighthouse-mobile:${PROJ_VERSION} .
