INSERT INTO AUTHORITY(NAME, SYSTEM_NAME) VALUES ('superadmin', 'ROLE_SUPER_ADMIN');
INSERT INTO AUTHORITY(NAME, SYSTEM_NAME) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITY(NAME, SYSTEM_NAME) VALUES ('ios-user', 'ROLE_IOS_USER');
INSERT INTO AUTHORITY(NAME, SYSTEM_NAME) VALUES ('android-user', 'ROLE_ANDROID_USER');
INSERT INTO AUTHORITY(NAME, SYSTEM_NAME) VALUES ('super-agent', 'ROLE_SUPER_AGENT');
INSERT INTO AUTHORITY(NAME, SYSTEM_NAME) VALUES ('agent', 'ROLE_AGENT');

INSERT INTO USERS(PHONE_NUMBER, ENABLED, ACCOUNT_NON_LOCKED, FIRST_NAME, SECOND_NAME, REGISTRATION_DATE, LAST_LOGIN)
VALUES ('79779873676', TRUE, TRUE, 'Олег', 'Цой', '2016-06-22 19:10:25-07', '2016-06-22 19:10:25-07');

INSERT INTO AUTHORITY_TO_USER(AUTHORITY_ID, USERS_ID)
VALUES ((SELECT ID FROM AUTHORITY WHERE SYSTEM_NAME = 'ROLE_SUPER_ADMIN'), (SELECT ID FROM USERS WHERE PHONE_NUMBER = '79779873676'));