CREATE TABLE RECOMMENDATION_FLAT
(
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    METRO_TIME              SMALLINT,
    DESCRIPTION             VARCHAR(5000),
    KITCHEN_AREA            NUMERIC(6, 1),
    LIVING_AREA             NUMERIC(6, 1),
    CEILING_HEIGHT          SMALLINT,
    REDECORATION            VARCHAR(250),
    BATHROOM                VARCHAR(50),
    BATHROOM_AMOUNT         SMALLINT,
    CONSTRUCTION_YEAR       SMALLINT,
    WALL_MATERIAL           VARCHAR(100),
    ELEVATOR_AMOUNT         SMALLINT,
    SERVICE_ELEVATOR_AMOUNT SMALLINT,
    PORCH_AMOUNT            SMALLINT,
    HEATING                 VARCHAR(107),
    PARKING                 VARCHAR(103),
    EXPERT_COMMENT          VARCHAR(1000),
    EXPERT_ID               BIGINT,
    FLAT_ID                 BIGINT,
    USER_ID                 BIGINT
);

COMMENT ON TABLE RECOMMENDATION_FLAT IS 'Детальное описание квартиры';
COMMENT ON COLUMN RECOMMENDATION_FLAT.DESCRIPTION IS 'Описание объявления';
COMMENT ON COLUMN RECOMMENDATION_FLAT.KITCHEN_AREA IS 'Площадь кухни -  m2';
COMMENT ON COLUMN RECOMMENDATION_FLAT.LIVING_AREA IS 'Площадь жилая -  m2';
COMMENT ON COLUMN RECOMMENDATION_FLAT.CEILING_HEIGHT IS 'Высота потолков - см.';
COMMENT ON COLUMN RECOMMENDATION_FLAT.REDECORATION IS 'Ремонт - задачи для машин лёнинга';
COMMENT ON COLUMN RECOMMENDATION_FLAT.BATHROOM IS 'Санузел - совмещенный / раздельный';
COMMENT ON COLUMN RECOMMENDATION_FLAT.BATHROOM_AMOUNT IS 'Санузел - шт.';
COMMENT ON COLUMN RECOMMENDATION_FLAT.CONSTRUCTION_YEAR IS 'Год постройки';
COMMENT ON COLUMN RECOMMENDATION_FLAT.WALL_MATERIAL IS 'Материал стен';
COMMENT ON COLUMN RECOMMENDATION_FLAT.ELEVATOR_AMOUNT IS 'Кол-во обычных лифтов';
COMMENT ON COLUMN RECOMMENDATION_FLAT.SERVICE_ELEVATOR_AMOUNT IS 'Кол-во грузовых лифтов';
COMMENT ON COLUMN RECOMMENDATION_FLAT.PORCH_AMOUNT IS 'Кол-во подъездов';
COMMENT ON COLUMN RECOMMENDATION_FLAT.HEATING IS 'Отопление';
COMMENT ON COLUMN RECOMMENDATION_FLAT.PARKING IS 'Парковка';
COMMENT ON COLUMN RECOMMENDATION_FLAT.EXPERT_COMMENT IS 'Комментарий эксперта';
COMMENT ON COLUMN RECOMMENDATION_FLAT.EXPERT_ID IS 'Идентификатор эксперта';
COMMENT ON COLUMN RECOMMENDATION_FLAT.FLAT_ID IS 'Идентификатор квартиры';
COMMENT ON COLUMN RECOMMENDATION_FLAT.USER_ID IS 'Идентификатор пользователя';