CREATE TABLE FLAT_IMAGE
(
    ID        BIGSERIAL PRIMARY KEY NOT NULL,
    NAME      VARCHAR(100),
    FILE_PATH VARCHAR(101),
    URL       VARCHAR(500),
    CONTENT   BYTEA,
    FLAT_ID   INT,
    FOREIGN KEY (FLAT_ID) REFERENCES FLAT (ID)
);

COMMENT ON TABLE FLAT_IMAGE IS 'Фотографии квартиры';
COMMENT ON COLUMN FLAT_IMAGE.NAME IS 'Наименование файла';
COMMENT ON COLUMN FLAT_IMAGE.FILE_PATH IS 'Путь к файлу';
COMMENT ON COLUMN FLAT_IMAGE.URL IS 'Оригинальная ссылка на файл';
COMMENT ON COLUMN FLAT_IMAGE.CONTENT IS 'Содержимое';
COMMENT ON COLUMN FLAT_IMAGE.FLAT_ID IS 'Идентификатор квартиры';
