CREATE TABLE BUILDING
(
    ID                      BIGSERIAL PRIMARY KEY NOT NULL,
    ADDRESS                 VARCHAR(100)       NOT NULL,
    LATITUDE                NUMERIC(9, 6)      NOT NULL,
    LONGITUDE               NUMERIC(9, 6)      NOT NULL,
    CONSTRUCTION_YEAR       SMALLINT,
    WALL_MATERIAL           VARCHAR(100),
    FLOOR_MATERIAL          VARCHAR(101),
    PROJECT_TYPE            VARCHAR(102),
    TOTAL_FLOORS            SMALLINT           NOT NULL,
    ELEVATOR_AMOUNT         SMALLINT,
    SERVICE_ELEVATOR_AMOUNT SMALLINT,
    AREA_FLATS_AMOUNT       SMALLINT,
    PARKING                 VARCHAR(103),
    PLAYGROUND              VARCHAR(104),
    TERRITORY               VARCHAR(105),
    UNINHABITED_F_FLOOR     BOOLEAN,
    METRO_DISTANCE          SMALLINT,
    METRO_TIME              SMALLINT,
    INFRASTRUCTURE          VARCHAR(106),
    HAS_GARBAGE_CHUTE       BOOLEAN,
    HAS_GAS                 BOOLEAN,
    HEATING                 VARCHAR(107),
    CAPITAL_REPAIR_DATE     TIMESTAMP,
    IS_HISTORICAL           BOOLEAN,
    AVG_METRE_PRICE         NUMERIC(18, 2),
    BUILDING_CLASS          VARCHAR(108),
    INVESTMENT_ATTRACTION   NUMERIC(10, 2),
    SOLD_FLATS_AMOUNT       SMALLINT,
    DISTRICT_ID             INT
);

COMMENT ON TABLE BUILDING IS 'Строения';
COMMENT ON COLUMN BUILDING.ADDRESS IS 'Адрес - Улица / номер дома / корпус / строение.';
COMMENT ON COLUMN BUILDING.LATITUDE IS 'Широта';
COMMENT ON COLUMN BUILDING.LONGITUDE IS 'Долгота';
COMMENT ON COLUMN BUILDING.CONSTRUCTION_YEAR IS 'Год постройки';
COMMENT ON COLUMN BUILDING.WALL_MATERIAL IS 'Материал стен';
COMMENT ON COLUMN BUILDING.FLOOR_MATERIAL IS 'Материал перекрытий';
COMMENT ON COLUMN BUILDING.PROJECT_TYPE IS 'Тип проекта';
COMMENT ON COLUMN BUILDING.TOTAL_FLOORS IS 'Этажность';
COMMENT ON COLUMN BUILDING.ELEVATOR_AMOUNT IS 'Кол-во обычных лифтов';
COMMENT ON COLUMN BUILDING.SERVICE_ELEVATOR_AMOUNT IS 'Кол-во грузовых лифтов';
COMMENT ON COLUMN BUILDING.AREA_FLATS_AMOUNT IS 'Количество квартир на площадке';
COMMENT ON COLUMN BUILDING.PARKING IS 'Парковка';
COMMENT ON COLUMN BUILDING.PLAYGROUND IS 'Детская площадка';
COMMENT ON COLUMN BUILDING.TERRITORY IS 'Территория - охраняемая / закрытая';
COMMENT ON COLUMN BUILDING.UNINHABITED_F_FLOOR IS 'Нежилой 1 этаж';
COMMENT ON COLUMN BUILDING.METRO_DISTANCE IS 'Расстояние до ближайшего метро в километрах.';
COMMENT ON COLUMN BUILDING.METRO_TIME IS 'Время до ближайшего метро';
COMMENT ON COLUMN BUILDING.INFRASTRUCTURE IS 'Инфраструктура - магазины / школы / сады / etc.';
COMMENT ON COLUMN BUILDING.HAS_GARBAGE_CHUTE IS 'Мусоропровод';
COMMENT ON COLUMN BUILDING.HAS_GAS IS 'Газ';
COMMENT ON COLUMN BUILDING.HEATING IS 'Отопление';
COMMENT ON COLUMN BUILDING.CAPITAL_REPAIR_DATE IS 'Кап ремонт - дата / нет';
COMMENT ON COLUMN BUILDING.IS_HISTORICAL IS 'Истор. ценность - есть / нет';
COMMENT ON COLUMN BUILDING.AVG_METRE_PRICE IS 'Ср. стоимость м2';
COMMENT ON COLUMN BUILDING.BUILDING_CLASS IS 'Класс дома / престижность - бизнесс / эконом / etc.';
COMMENT ON COLUMN BUILDING.INVESTMENT_ATTRACTION IS 'Инвестиционная привлекательность -  - окупаемость от сдачи в аренду в годах';
COMMENT ON COLUMN BUILDING.SOLD_FLATS_AMOUNT IS 'Количество проданных квартир';
COMMENT ON COLUMN BUILDING.DISTRICT_ID IS 'Идентификатор района';