CREATE TABLE MOBILE_USER
(
    ID                 BIGSERIAL PRIMARY KEY NOT NULL,
    PHONE_NUMBER       VARCHAR(50) UNIQUE    NOT NULL,
    ENABLED            BOOLEAN               NOT NULL,
    ACCOUNT_NON_LOCKED BOOLEAN               NOT NULL,
    USER_AGENT         VARCHAR(500),
    FIRST_NAME         VARCHAR(500),
    SECOND_NAME        VARCHAR(500),
    LAST_NAME          VARCHAR(500),
    BIRTH_DATE         DATE,
    REGISTRATION_DATE  TIMESTAMP             NOT NULL,
    LAST_LOGIN         TIMESTAMP             NOT NULL
);

COMMENT ON TABLE MOBILE_USER IS 'Пользователь';
COMMENT ON COLUMN MOBILE_USER.PHONE_NUMBER IS 'Номер телефона';
COMMENT ON COLUMN MOBILE_USER.ENABLED IS 'Активен';
COMMENT ON COLUMN MOBILE_USER.ACCOUNT_NON_LOCKED IS 'Не заблокирован';
COMMENT ON COLUMN MOBILE_USER.USER_AGENT IS 'User agent';
COMMENT ON COLUMN MOBILE_USER.FIRST_NAME IS 'Имя';
COMMENT ON COLUMN MOBILE_USER.SECOND_NAME IS 'Фамилия';
COMMENT ON COLUMN MOBILE_USER.LAST_NAME IS 'Отчество';
COMMENT ON COLUMN MOBILE_USER.BIRTH_DATE IS 'Дата рождения';
COMMENT ON COLUMN MOBILE_USER.REGISTRATION_DATE IS 'Дата регистрации';

--====================================================================================================================--

CREATE TABLE MOBILE_AUTHORITY
(
    ID          BIGSERIAL PRIMARY KEY NOT NULL,
    NAME        VARCHAR(200)          NOT NULL,
    SYSTEM_NAME VARCHAR(100) UNIQUE   NOT NULL
);

COMMENT ON TABLE MOBILE_AUTHORITY IS 'Возможные права пользователя';
COMMENT ON COLUMN MOBILE_AUTHORITY.NAME IS 'Наименование';
COMMENT ON COLUMN MOBILE_AUTHORITY.SYSTEM_NAME IS 'Системное наименование';

--====================================================================================================================--

CREATE TABLE MOBILE_AUTHORITY_TO_USER
(
    ID           BIGSERIAL PRIMARY KEY NOT NULL,
    USERS_ID     BIGINT                NOT NULL,
    FOREIGN KEY (USERS_ID) REFERENCES MOBILE_USER (ID),
    AUTHORITY_ID BIGINT                NOT NULL,
    FOREIGN KEY (AUTHORITY_ID) REFERENCES MOBILE_AUTHORITY (ID)
);

COMMENT ON TABLE MOBILE_AUTHORITY_TO_USER IS 'Права пользователя';
COMMENT ON COLUMN MOBILE_AUTHORITY_TO_USER.USERS_ID IS 'Идентификатор пользователя';
COMMENT ON COLUMN MOBILE_AUTHORITY_TO_USER.AUTHORITY_ID IS 'Идентификатор права MOBILE_AUTHORITY';
