server:
  port: 8004
  servlet:
    context-path: /mobile

spring:
  application:
      name: mobile-service
  datasource:
    url: ${shared-database.url}
    username: ${shared-database.username}
    password: ${shared-database.password}
    driver-class-name: ${shared-database.driver}
  flyway:
    enabled: true
    locations: classpath:/db/migration/${shared-database.type}
    ignore-missing-migrations: true
    out-of-order: true
  jpa:
    properties:
      hibernate:
        default_schema: public
    show-sql: false

# --------------------------------------------- Shared properties ------------------------------------------------------
domain:
  name: purevaluation
  host: purevaluation.ru
  url: https://purevaluation.ru

shared-database:
  type: postgres
  url: jdbc:postgresql://localhost:5432/lighthousedb
  username: postgres
  password: password
  driver: org.postgresql.Driver

security:
  enabled: true
  jwt:
    uri: /auth/**
    secret: 12k;msdfg/!@#$%sd
    expiration: "#{10*24*60*60}"
    claims:
      authorities:
        claimName: authorities
      details:
        claimName: details
        userId: userId
        userBirthDate: userBirthDate
        userFirstName: userFirstName
        userSecondName: userSecondName
        userLastName: userLastName

integration:
  uri:
    user: /integration/user