#!/usr/bin/env sh

ENV=${1:-gradle}

function gradle_properties {
    grep "${1}" ${ENV}.properties|cut -d'=' -f2
}

PROJ_NAME=lighthouse-mobile-main
PROJ_VERSION=$(gradle_properties 'lProjectVersion')
DOCKER_REGISTRY_LOGIN=tsoyolv

printf '============================================ ATTENTION! YOU HAVE TO RUN COMMAND FROM ROOT DIRECTORY ==============================================\n\n'

printf '============================================ Project versions: '
printf ${PROJ_NAME}
printf ' '
printf ${PROJ_VERSION}
printf " ============================================\n\n"

printf '============================================ Docker HUB registry: '
printf " login: "
printf ${DOCKER_REGISTRY_LOGIN}
printf " ============================================\n\n"

# Read Password
printf "ENTER Docker password: "
read -s password
echo
printf "Password entered\n\n"
docker logout
docker login --username ${DOCKER_REGISTRY_LOGIN} --password $password

./gradlew clean
./gradlew bootJar
mkdir -p build/dependency && (cd build/dependency; jar -xf ../libs/*.jar)

docker build -f docker/Dockerfile -t ${PROJ_NAME}:${PROJ_VERSION} .
docker tag ${PROJ_NAME}:${PROJ_VERSION} ${DOCKER_REGISTRY_LOGIN}/${PROJ_NAME}:${PROJ_VERSION}
docker push ${DOCKER_REGISTRY_LOGIN}/${PROJ_NAME}:${PROJ_VERSION}

docker tag ${PROJ_NAME}:${PROJ_VERSION} ${DOCKER_REGISTRY_LOGIN}/${PROJ_NAME}:latest
docker push ${DOCKER_REGISTRY_LOGIN}/${PROJ_NAME}:latest